"""Add pinned field to direct messages

Revision ID: 0b271cc01dcc
Revises: 6ecdb9f4ac9d
Create Date: 2025-02-23 12:17:45.027583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b271cc01dcc'
down_revision = '6ecdb9f4ac9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pinned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_message', schema=None) as batch_op:
        batch_op.drop_column('pinned')

    # ### end Alembic commands ###
