"""recreate_follow_tables

Revision ID: 2b0956318aac
Revises: d39c2407c3b5
Create Date: 2025-02-24 20:07:51.006528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0956318aac'
down_revision = 'd39c2407c3b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_follow_constraint', ['follower_id', 'followed_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['followed_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['follower_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['follower_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['followed_id'], ['id'])
        batch_op.drop_constraint('unique_follow_constraint', type_='unique')

    # ### end Alembic commands ###
