"""Add pinned field to direct messages - 2

Revision ID: d39c2407c3b5
Revises: 0b271cc01dcc
Create Date: 2025-02-24 20:04:29.615364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39c2407c3b5'
down_revision = '0b271cc01dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_follow', ['follower_id', 'followed_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['followed_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['follower_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['followed_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['follower_id'], ['id'])
        batch_op.drop_constraint('unique_follow', type_='unique')

    # ### end Alembic commands ###
